name: CI/CD

on:
  push:
    branches:
      - "**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy artifacts
        run: |
          mkdir deploy
          cp -R dist/* deploy/

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          rm: true
          source: "deploy/*"
          strip_components: 1
          target: "/usr/share/nginx/html/deploy"
        if: github.ref == 'refs/heads/main'
